on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          package-name: release-please-action

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20
        if: ${{ steps.release.outputs.release_created }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      - name: login
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      - name: build and push
        run: |
          TAG=docker.pkg.github.com/${GITHUB_REPOSITORY}/grn-gcal-sync:v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          docker build -t $TAG .
          docker push $TAG
        if: ${{ steps.release.outputs.release_created }}
